"""add visits count field

Revision ID: 6949506d5fdb
Revises: 954a88cee546
Create Date: 2025-08-15 12:50:32.818755

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6949506d5fdb"
down_revision: str | Sequence[str] | None = "954a88cee546"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "link", sa.Column("visits_count", sa.Integer(), nullable=True, default=0)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("link", "visits_count")
    # ### end Alembic commands ###
